name: CI-CHECKS

on: [push]

jobs:
  run-phpcs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        uses: php-actions/composer@v6
      - name: Run PHPCodesniffer
        run: ./vendor/bin/phpcs -p -s --standard=phpcs.xml src tests
  run-php-stan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        uses: php-actions/composer@v6
      - name: Run PHPStan
        run: vendor/bin/phpstan analyse -c phpstan.neon.dist
  run-php-unit-tests:
    needs: [ run-phpcs, run-php-stan ]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        uses: php-actions/composer@v6
      - name: Execute tests
        run: vendor/bin/phpunit -c phpunit.xml --colors=always --verbose --testdox